# Generated by Django 2.1.1 on 2018-10-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_mainshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=10)),
                ('typename', models.CharField(max_length=20)),
                ('typesort', models.IntegerField(max_length=11)),
                ('childtypenames', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'foodtypes',
            },
        ),
    ]
