# Generated by Django 2.1.1 on 2018-10-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=20)),
                ('productimg', models.CharField(max_length=150)),
                ('productprice', models.CharField(max_length=10)),
                ('productnum', models.CharField(max_length=10)),
                ('userid', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
