# Generated by Django 2.1.1 on 2018-10-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_cartgoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartgoods',
            name='ischose',
            field=models.BooleanField(default=False),
        ),
    ]
